console.log("abc".padStart(10)); // Output: "       abc"
console.log("abc".padStart(10, "foo")); // Output: "foofoofabc"
console.log("abc".padStart(6, "123465")); // Output: "123abc"
console.log("abc".padStart(8, "0")); // Output: "00000abc"
console.log("abc".padStart(1)); // Output: "abc"
